let con = document.querySelector('.content');
const btn = document.querySelector('.btn'); 
const eng = document.querySelector('.word'); 
const mean = document.querySelector('.mean'); 
const h1 = document.querySelector('.g');

const word = [
  ["abundant", "more than enough; plentiful"],
  ["benevolent", "kind and willing to help others"],
  ["cautious", "careful to avoid danger or mistakes"],
  ["diligent", "hard-working and careful"],
  ["eloquent", "able to express ideas clearly and beautifully"],
  ["fragile", "easily broken or damaged"],
  ["gratitude", "thankfulness"],
  ["hesitant", "unsure or slow to make a decision"],
  ["impartial", "fair; not favoring one side"],
  ["meticulous", "very careful about small details"],
  ["obsolete", "no longer useful or in use"],
  ["persistent", "continuing despite difficulties"],
  ["resilient", "able to recover from difficulties"],
  ["skeptical", "not easily convinced; doubtful"],
  ["vivid", "very clear, detailed, or bright"],
  ["adapt", "to adjust to a new situation"],
  ["ambiguous", "having more than one possible meaning"],
  ["articulate", "able to express ideas clearly"],
  ["compassion", "sympathy and concern for others"],
  ["contemplate", "to think deeply about something"],
  ["curious", "eager to learn or know something"],
  ["deteriorate", "to become worse over time"],
  ["dread", "to fear or worry about something"],
  ["elaborate", "detailed and carefully developed"],
  ["empathy", "the ability to understand another person's feelings"],
  ["exquisite", "extremely beautiful or delicate"],
  ["fascinate", "to attract someone's interest strongly"],
  ["formidable", "very difficult or impressive"],
  ["imminent", "about to happen soon"],
  ["ingenious", "clever and inventive"],
  ["inevitable", "certain to happen"],
  ["magnificent", "extremely impressive or beautiful"],
  ["notorious", "famous for something bad"],
  ["novel", "new and unusual"],
  ["persevere", "to continue despite difficulties"],
  ["plausible", "seeming reasonable or possible"],
  ["profound", "very deep or meaningful"],
  ["reluctant", "unwilling or hesitant"],
  ["scrutinize", "to examine very carefully"],
  ["substantial", "large or considerable in size or importance"],
  ["versatile", "able to be used in many different ways"],
  ["wary", "careful because of possible danger"],
  ["zealous", "very enthusiastic and devoted"],
  ["coherent", "clear, logical, and easy to understand"],
  ["conventional", "usual or traditional"],
  ["eccentric", "unusual or unconventional"],
  ["feasible", "possible and practical"],
  ["genuine", "real and authentic"],
  ["humble", "not thinking you are better than others"],
  ["innovative", "introducing new ideas or methods"],
  ["intricate", "very detailed or complicated"],
  ["justify", "to give a good reason for something"],
  ["lucid", "clear and easy to understand"],
  ["mundane", "ordinary and not interesting"],
  ["optimistic", "expecting good things to happen"],
  ["pragmatic", "focused on practical solutions"],
  ["redundant", "unnecessary because something similar already exists"],
  ["spontaneous", "happening naturally without planning"],
  ["tenacious", "determined and unwilling to give up"],
  ["tranquil", "calm and peaceful"],
  ["unprecedented", "never having happened before"],
  ["vulnerable", "easily harmed or affected"],
  ["wisdom", "the ability to make good decisions based on knowledge"],
  ["yearn", "to strongly desire something"],
  ["zeal", "great enthusiasm or energy"],
  ["astute", "clever and quick to understand"],
  ["bewildered", "very confused"],
  ["conspicuous", "easy to notice"],
  ["deceive", "to trick someone"],
  ["diminish", "to become smaller or less"],
  ["discerning", "good at recognizing differences and quality"],
  ["diverse", "including many different types"],
  ["dubious", "uncertain or doubtful"],
  ["enhance", "to improve something"],
  ["enormous", "extremely large"],
  ["explicit", "clearly stated or shown"],
  ["flawless", "without any mistakes or defects"],
  ["formulate", "to develop or create carefully"],
  ["gregarious", "friendly and enjoying the company of others"],
  ["hypothetical", "based on a possible situation rather than reality"],
  ["impulsive", "acting suddenly without thinking"],
  ["indifferent", "not interested or concerned"],
  ["inquisitive", "curious and eager to learn"],
  ["judicious", "showing good judgment"],
  ["lethargic", "having little energy"],
  ["mandatory", "required by rules or law"],
  ["merit", "the quality of being deserving or valuable"],
  ["negligent", "failing to give proper care or attention"],
  ["perplexed", "confused and uncertain"],
  ["precise", "exact and accurate"],
  ["rational", "based on reason and logic"],
  ["reconcile", "to restore agreement or harmony"],
  ["remarkable", "worthy of attention or admiration"],
  ["reticent", "unwilling to speak much"],
  ["scrupulous", "extremely careful and honest"],
  ["sophisticated", "advanced, refined, or complex"],
  ["tedious", "boring because it is repetitive or lengthy"],
  ["transient", "lasting only for a short time"],
  ["unanimous", "completely agreed upon by everyone"],
  ["validate", "to confirm that something is correct or valid"],
  ["vigilant", "watchful and alert"],
  ["volatile", "likely to change suddenly"],
  ["whimsical", "playfully unusual or imaginative"],
  ["wary", "careful because something may be dangerous"],
  ["withstand", "to resist or survive something difficult"],
  ["abrupt", "sudden and unexpected"],
  ["adversity", "a difficult or unpleasant situation"],
  ["conundrum", "a difficult problem or question"],
  ["discreet", "careful not to attract attention"],
  ["eloquence", "the ability to express ideas beautifully"],
  ["exaggerate", "to make something seem greater than it is"],
  ["frugal", "careful about spending money or resources"],
  ["inept", "lacking skill or ability"],
  ["obsolete", "no longer useful or commonly used"],
  ["reputable", "having a good reputation"],
  ["versatile", "able to adapt to many different uses or situations"],
  ["abstruse", "difficult to understand because it is very complex"],
  ["acquiesce", "to accept something reluctantly without protesting"],
  ["acrimonious", "angry and bitter, especially in an argument"],
  ["ameliorate", "to make a bad situation better"],
  ["anachronistic", "belonging to a different time period than the one being considered"],
  ["antithetical", "completely opposite in nature or meaning"],
  ["belligerent", "hostile and eager to argue or fight"],
  ["circumspect", "careful to avoid risks or mistakes"],
  ["cogent", "clear, logical, and convincing"],
  ["convoluted", "extremely complicated and difficult to understand"],
  ["deleterious", "causing harm or damage"],
  ["demagogue", "a political leader who gains support by appealing to emotions"],
  ["derivative", "copied or developed from something else"],
  ["dichotomy", "a division between two strongly contrasting things"],
  ["disparate", "very different from each other"],
  ["egregious", "remarkably bad or unacceptable"],
  ["equivocal", "open to more than one interpretation"],
  ["esoteric", "understood by only a small group with specialized knowledge"],
  ["exacerbate", "to make a problem or situation worse"],
  ["fastidious", "very careful about details and standards"],
  ["grandiloquent", "using language that sounds impressive but is often overly complicated"],
  ["incongruous", "not matching or fitting with something else"],
  ["incontrovertible", "impossible to deny or dispute"],
  ["indefatigable", "able to continue working without becoming tired"],
  ["ineffable", "too great or beautiful to be described in words"],
  ["intransigent", "unwilling to change one's opinion or position"],
  ["inveterate", "having a habit or attitude that has existed for a long time"],
  ["juxtapose", "to place two things close together to compare them"],
  ["laconic", "using very few words"],
  ["magniloquent", "using grand or exaggerated language"],
  ["misanthropic", "disliking or distrusting humanity"],
  ["nefarious", "wicked or extremely immoral"],
  ["obfuscate", "to deliberately make something confusing or unclear"],
  ["ostentatious", "designed to attract attention by being showy"],
  ["paradoxical", "seemingly contradictory but possibly true"],
  ["perfunctory", "done with little care, effort, or enthusiasm"],
  ["perspicacious", "having a sharp ability to understand things"],
  ["pragmatic", "dealing with problems in a practical way"],
  ["proclivity", "a natural tendency to behave in a particular way"],
  ["prodigious", "extremely large, impressive, or remarkable"],
  ["quintessential", "representing the most typical or perfect example"],
  ["recalcitrant", "stubbornly refusing to obey or cooperate"],
  ["reprehensible", "deserving strong criticism or blame"],
  ["sagacious", "having good judgment and wisdom"],
  ["superfluous", "unnecessary or excessive"],
  ["surreptitious", "done secretly to avoid being noticed"],
  ["taciturn", "habitually quiet and not talkative"],
  ["tenuous", "weak, uncertain, or not strongly supported"],
  ["ubiquitous", "present or found everywhere"],
  ["vociferous", "expressing opinions loudly and forcefully"],
  ["abnegation", "the act of giving up one's own interests or desires"],
  ["apocryphal", "widely believed but probably not true"],
  ["circumlocution", "using many words instead of saying something directly"],
  ["compunction", "a feeling of guilt about doing something wrong"],
  ["conflagration", "a large and destructive fire"],
  ["conundrum", "a difficult and confusing problem"],
  ["deleterious", "causing serious harm or damage"],
  ["disquisition", "a long, detailed explanation or discussion"],
  ["effrontery", "shameless boldness or disrespectful behavior"],
  ["enervate", "to weaken or drain someone's energy"],
  ["epistemology", "the study of knowledge and how we know things"],
  ["equanimity", "calmness and self-control, especially during difficulty"],
  ["extrapolate", "to estimate something using known information"],
  ["fastidious", "extremely careful about accuracy and details"],
  ["gregarious", "fond of socializing and being around people"],
  ["iconoclast", "someone who challenges traditional beliefs or customs"],
  ["inimical", "harmful or hostile to something"],
  ["insidious", "harmful in a gradual and difficult-to-notice way"],
  ["intransigent", "unwilling to compromise or change one's position"],
  ["lachrymose", "tearful or likely to cause sadness"],
  ["magnanimous", "generous and forgiving toward others"],
  ["mendacious", "dishonest or deliberately untruthful"],
  ["munificent", "extremely generous, especially with money or gifts"],
  ["obsequious", "excessively eager to please someone important"],
  ["obstreperous", "noisy, difficult to control, or unwilling to obey"],
  ["paradigm", "a typical model or pattern of something"],
  ["parsimonious", "extremely unwilling to spend money or resources"],
  ["perfidious", "deliberately unfaithful or deceitful"],
  ["perspicuity", "the quality of being clear and easy to understand"],
  ["plethora", "a very large amount of something"],
  ["precipitous", "happening suddenly or dropping very steeply"],
  ["propensity", "a natural tendency to behave in a certain way"],
  ["recalcitrant", "stubbornly refusing to obey or cooperate"],
  ["recondite", "little known and difficult to understand"],
  ["redoubtable", "worthy of respect or fear because of great ability"],
  ["reprobate", "a morally unprincipled person"],
  ["sagacious", "having excellent judgment and wisdom"],
  ["solipsistic", "focused entirely on one's own thoughts or experiences"],
  ["specious", "appearing reasonable or true but actually false"],
  ["supercilious", "behaving as though one is superior to others"],
  ["surreptitious", "done secretly to avoid being noticed"],
  ["sycophant", "a person who flatters powerful people to gain advantages"],
  ["tantamount", "equivalent in effect or meaning"],
  ["temerity", "excessive confidence or boldness"],
  ["ubiquitous", "seeming to exist or appear everywhere"],
  ["vacillate", "to repeatedly change between different opinions or choices"],
  ["veracity", "truthfulness or accuracy"],
  ["vitriolic", "filled with bitter criticism or hatred"],
  ["vociferous", "expressing opinions loudly and forcefully"],
  ["zeitgeist", "the defining ideas and attitudes of a particular period"],
  ["acumen", "the ability to make quick and accurate judgments"],
  ["adumbrate", "to describe something without giving many details"],
  ["alacrity", "great eagerness and speed in doing something"],
  ["apathy", "a lack of interest, enthusiasm, or concern"],
  ["arcane", "known or understood by very few people"],
  ["assiduous", "showing great care, effort, and persistence"],
  ["avarice", "an extreme desire for wealth"],
  ["belie", "to give a false impression of something"],
  ["bombastic", "using language that sounds important but has little meaning"],
  ["capricious", "changing suddenly and unpredictably"],
  ["chicanery", "dishonest methods used to achieve something"],
  ["cogitate", "to think carefully about something"],
  ["complacency", "excessive satisfaction that prevents improvement or caution"],
  ["contemptuous", "showing that you think someone is beneath you"],
  ["corroborate", "to confirm something with additional evidence"],
  ["credulous", "too willing to believe something without sufficient evidence"],
  ["disingenuous", "not sincere or honest, especially when pretending to be"],
  ["dogmatic", "expressing opinions as if they are unquestionably true"],
  ["duplicity", "deliberate dishonesty or deception"],
  ["enigma", "something mysterious or difficult to understand"],
  ["ephemeral", "existing or lasting for a very short time"],
  ["erudite", "having extensive knowledge gained through study"],
  ["exculpate", "to prove that someone is not responsible for wrongdoing"],
  ["expedient", "convenient or practical rather than necessarily morally right"],
  ["extol", "to praise someone or something highly"],
  ["facetious", "treating a serious subject in a deliberately humorous way"],
  ["fallacious", "based on faulty reasoning or false ideas"],
  ["fervent", "showing intense enthusiasm or passion"],
  ["fortuitous", "happening by chance, especially in a fortunate way"],
  ["frivolous", "not serious or lacking a sensible purpose"],
  ["harangue", "a long and forceful speech or criticism"],
  ["impecunious", "having little or no money"],
  ["impertinent", "rude or disrespectful"],
  ["incongruity", "a lack of agreement or harmony"],
  ["ineptitude", "lack of skill or ability"],
  ["inscrutable", "difficult or impossible to understand"],
  ["intrepid", "extremely brave and willing to face danger"],
  ["invective", "insulting or abusive language"],
  ["irascible", "easily made angry"],
  ["magnanimity", "generosity and forgiveness toward others"],
  ["maladroit", "clumsy or lacking skill"],
  ["malleable", "easily influenced, changed, or shaped"],
  ["mercurial", "changing moods or behavior quickly and unpredictably"],
  ["mitigate", "to make something less severe or harmful"],
  ["nonchalant", "calm and unconcerned, even in a difficult situation"],
  ["obdurate", "stubbornly refusing to change one's opinion"],
  ["opprobrium", "strong public criticism or disgrace"],
  ["ostensible", "appearing to be true or genuine but possibly not so"],
  ["pernicious", "having a harmful effect, especially gradually"],
  ["prevaricate", "to avoid giving a direct or truthful answer"],
  ["prolix", "using too many words"],
  ["propitious", "likely to lead to a successful or favorable outcome"],
  ["reticent", "not willing to speak freely about something"],
  ["reverent", "showing deep respect"],
  ["stoic", "remaining calm and unemotional during difficulty"],
  ["surfeit", "an excessive amount of something"],
  ["trenchant", "strong, clear, and effective, especially in criticism"],
  ["tumultuous", "full of confusion, disorder, or strong emotion"],
  ["unassailable", "impossible to challenge or defeat"],
  ["undermine", "to gradually weaken something"],
  ["untenable", "impossible to maintain or defend"],
  ["verbose", "using more words than necessary"],
  ["vindicate", "to prove that someone was right or not guilty"],
  ["wanton", "deliberately excessive or reckless"],
  ["zealous", "extremely enthusiastic and devoted"],
  ["abjure", "to formally reject or give up something"],
  ["adumbrate", "to give a brief or incomplete explanation of something"],
  ["anathema", "something strongly disliked or considered unacceptable"],
  ["antediluvian", "extremely old-fashioned or outdated"],
  ["apotheosis", "the highest point of development or excellence"],
  ["assiduous", "showing great care, effort, and persistence"],
  ["auspicious", "suggesting that something is likely to succeed"],
  ["bellicose", "demonstrating a willingness to fight or argue"],
  ["calumny", "a false statement intended to damage someone's reputation"],
  ["chicanery", "clever but dishonest methods used to achieve something"],
  ["circumspection", "careful consideration of possible consequences"],
  ["corroborate", "to confirm something using additional evidence"],
  ["crepuscular", "relating to the twilight period around sunrise or sunset"],
  ["cupidity", "an excessive desire for wealth or possessions"],
  ["deference", "respectful submission to another person's opinion or authority"],
  ["desultory", "lacking a clear plan, purpose, or enthusiasm"],
  ["diaphanous", "very light, delicate, and almost transparent"],
  ["dissemble", "to hide one's true feelings or intentions"],
  ["ebullient", "extremely cheerful, enthusiastic, and energetic"],
  ["efficacious", "successful in producing the intended result"],
  ["encomium", "a speech or piece of writing expressing strong praise"],
  ["ennui", "a feeling of boredom and lack of interest"],
  ["execrable", "extremely bad or unpleasant"],
  ["expatiate", "to speak or write at length about something"],
  ["extemporaneous", "done or spoken without preparation"],
  ["fastidious", "very attentive to detail and difficult to please"],
  ["fatuous", "silly or foolish, especially in a self-satisfied way"],
  ["fecund", "highly productive or capable of producing abundant results"],
  ["florid", "excessively elaborate or complicated in style"],
  ["garrulous", "talking excessively, especially about unimportant things"],
  ["harangue", "a long and forceful speech criticizing someone"],
  ["ignominious", "deserving shame or disgrace"],
  ["impecunious", "having little or no money"],
  ["imperturbable", "remaining calm despite difficult circumstances"],
  ["inchoate", "not yet fully developed or organized"],
  ["ineffable", "too extraordinary to be expressed in words"],
  ["insouciant", "showing little concern or worry"],
  ["invective", "insulting or abusive language"],
  ["jejune", "lacking interest, maturity, or sophistication"],
  ["juxtaposition", "placing contrasting things together for comparison"],
  ["lachrymose", "tearful or excessively sad"],
  ["logorrhea", "excessive and often meaningless talking"],
  ["lugubrious", "looking or sounding extremely sad"],
  ["mercurial", "changing moods or behavior quickly and unpredictably"],
  ["mordant", "sharp and critical, often in a humorous way"],
  ["neologism", "a newly created word or expression"],
  ["obdurate", "stubbornly refusing to change one's opinion"],
  ["pellucid", "extremely clear and easy to understand"],
  ["perspicacious", "having a very sharp understanding of things"],
  ["pusillanimous", "lacking courage or determination"],
  ["recalcitrance", "stubborn resistance to authority or control"],
  ["recondite", "obscure and difficult to understand"],
  ["sesquipedalian", "characterized by the use of unusually long words"],
  ["trenchant", "sharp, forceful, and effective"],
  ["vicissitude", "a change in circumstances, especially an unpleasant one"],
  ["zephyr", "a gentle, mild breeze"]
];

btn.addEventListener('click',()=>{
    let words = Math.floor(word.length*Math.random());
    eng.innerHTML = word[words][0];
    mean.innerHTML = word[words][1];
})
